# Copyright 2024 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Luca Colagrande <colluca@iis.ee.ethz.ch>

# Usage of absolute paths is required to externally include this Makefile
MK_DIR   := $(dir $(realpath $(lastword $(MAKEFILE_LIST))))
DATA_DIR := $(realpath $(MK_DIR)/data)
SRC_DIR  := $(realpath $(MK_DIR)/src)

KMEANS_DATA_CFG ?= $(DATA_DIR)/params.json
SECTION  ?=

APP     ?= kmeans
SRCS    ?= $(realpath $(SRC_DIR)/main.c)
INCDIRS ?= $(DATA_DIR) $(SRC_DIR)

DATAGEN_PY = $(MK_DIR)/scripts/datagen.py
DATA_H     = $(DATA_DIR)/data.h

$(DATA_H): $(DATAGEN_PY) $(KMEANS_DATA_CFG)
	$< -c $(KMEANS_DATA_CFG) --no-gui --section="$(SECTION)" $@

.PHONY: clean-data clean

clean-data:
	rm -f $(DATA_H)

clean: clean-data
